### ISSUE TITLE
while installation found Problem 1

### ISSUE THREAD

**Issue by nishant-befree** [charlesportwoodii/yii2-api#2]
The requested PHP extension ext-sodium >=2.0.0 is missing from your system. Install or enable PHP's sodium extension.

is this php_libsodium ?

**Comment by charlesportwoodii** [comment]
@nishant-befree Correct. Grab the latest 2.0.x release from https://github.com/jedisct1/libsodium-php/releases/tag/2.0.4.

**Comment by charlesportwoodii** [comment]
@nishant-befree As a separate note, the provided docker configuration has libsodium and ext-sodium bundled. I'd recommend using it if you're looking to play around with this repository.
